FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Instalar dependencias del sistema para OpenCV
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo requirements.txt
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente de la aplicación
COPY . /app

# Exponer el puerto
EXPOSE 8000

# Ejecutar la aplicación con Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
